# A simple example of ClusterConfig object:
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: anton-test
  region: us-east-2
  version: "1.22"
managedNodeGroups:
  - name: anton-ng
    instanceType: t2.small
    minSize: 3
    maxSize: 6
    spot: true
# fargateProfiles:
#   - name: anton-fp-default
#     selectors:
#       # All workloads in the "default" Kubernetes namespace will be
#       # scheduled onto Fargate:
#       - namespace: default
#       # All workloads in the "kube-system" Kubernetes namespace will be
#       # scheduled onto Fargate:
#       - namespace: kube-system
# vpc:
#   id: "vpc-014f7d368c6975e30"  # (optional, must match VPC ID used for each subnet below)
#   cidr: "192.168.0.0/16"       # (optional, must match CIDR used by the given VPC)
#   subnets:
#     # must provide 'private' and/or 'public' subnets by availibility zone as shown
#     private:
#       us-east-2a:
#         id: "subnet-0dddddf1abe3059e7"
#         cidr: "192.168.96.0/19" # (optional, must match CIDR used by the given subnet)

#       us-east-2b:
#         id: "subnet-03e70663077f6890c"
#         cidr: "192.168.160.0/19"  # (optional, must match CIDR used by the given subnet)

#       us-east-2c:
#         id: "subnet-096489d3b6f6cd83c"
#         cidr: "192.168.128.0/19"   # (optional, must match CIDR used by the given subnet)
#     public:
#       us-east-2a:
#         id: "subnet-02785443ec870e89f"
#         cidr: "192.168.0.0/19" # (optional, must match CIDR used by the given subnet)

#       us-east-2b:
#         id: "subnet-058777c877a9344d9"
#         cidr: "192.168.64.0/19"  # (optional, must match CIDR used by the given subnet)

#       us-east-2c:
#         id: "subnet-0795b3b2de56db28f"
#         cidr: "192.168.32.0/19"   # (optional, must match CIDR used by the given subnet)