controller:
  replicaCount: 3
  nodeSelector: {
    role: system,
    beta.kubernetes.io/os: linux
  }
  metrics:
    enabled: true
    serviceMonitor: 
      enabled: true
      additionalLabels: {
        release: "prometheus"
      }

defaultBackend:
  nodeSelector: {
    role: system,
    beta.kubernetes.io/os: linux
  }
  